const data = {
  employee: [
    {
      Name: "Sarah Johnson",
      Email: "sarah.johnson@example.com",
      Phone: 5556667777,
      Address: "789 Elm Avenue, Townsville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "David Lee",
      Email: "david.lee@example.com",
      Phone: 3334445555,
      Address: "456 Oak Street, Cityville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Laura Davis",
      Email: "laura.davis@example.com",
      Phone: 8889990000,
      Address: "101 Maple Road, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "James Smith",
      Email: "james.smith@example.com",
      Phone: 1112223333,
      Address: "555 Pine Lane, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Jennifer Brown",
      Email: "jennifer.brown@example.com",
      Phone: 6667778888,
      Address: "222 Cedar Avenue, Suburbia",
      Degree: "Bachelor of Arts",
      Title: "Content Writer",
    },
    {
      Name: "Employee 11",
      Email: "employee11@example.com",
      Phone: 1112223334,
      Address: "123 Elm Street, Cityville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 12",
      Email: "employee12@example.com",
      Phone: 2223334445,
      Address: "456 Oak Avenue, Townsville",
      Degree: "Master of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "Employee 13",
      Email: "employee13@example.com",
      Phone: 3334445556,
      Address: "789 Pine Road, Villagetown",
      Degree: "Bachelor of Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 14",
      Email: "employee14@example.com",
      Phone: 4445556667,
      Address: "101 Cedar Lane, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Employee 15",
      Email: "employee15@example.com",
      Phone: 5556667778,
      Address: "555 Maple Street, Suburbia",
      Degree: "Bachelor of Engineering",
      Title: "Project Manager",
    },
    {
      Name: "Employee 16",
      Email: "employee16@example.com",
      Phone: 6667778889,
      Address: "789 Oak Lane, Cityville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 17",
      Email: "employee17@example.com",
      Phone: 7778889991,
      Address: "456 Pine Avenue, Townsville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 18",
      Email: "employee18@example.com",
      Phone: 8889990002,
      Address: "123 Cedar Road, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "Employee 19",
      Email: "employee19@example.com",
      Phone: 9990001113,
      Address: "555 Elm Lane, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Employee 20",
      Email: "employee20@example.com",
      Phone: 1234567004,
      Address: "101 Oak Street, Suburbia",
      Degree: "Bachelor of Arts",
      Title: "Content Writer",
    },
    {
      Name: "Employee 21",
      Email: "employee21@example.com",
      Phone: 2345678015,
      Address: "789 Maple Avenue, Cityville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 22",
      Email: "employee22@example.com",
      Phone: 3456789126,
      Address: "456 Pine Lane, Townsville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 23",
      Email: "employee23@example.com",
      Phone: 4567890237,
      Address: "555 Elm Road, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "Employee 24",
      Email: "employee24@example.com",
      Phone: 5678901348,
      Address: "101 Cedar Street, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Employee 25",
      Email: "employee25@example.com",
      Phone: 6789012459,
      Address: "789 Oak Avenue, Suburbia",
      Degree: "Bachelor of Engineering",
      Title: "Project Manager",
    },
    {
      Name: "Employee 26",
      Email: "employee26@example.com",
      Phone: 7890123560,
      Address: "123 Main Lane, Cityville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 27",
      Email: "employee27@example.com",
      Phone: 8901234671,
      Address: "456 Elm Road, Townsville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 28",
      Email: "employee28@example.com",
      Phone: 9012345782,
      Address: "101 Pine Street, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "Employee 29",
      Email: "employee29@example.com",
      Phone: 1234567893,
      Address: "555 Oak Lane, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Employee 30",
      Email: "employee30@example.com",
      Phone: 2345678904,
      Address: "789 Cedar Avenue, Suburbia",
      Degree: "Bachelor of Arts",
      Title: "Content Writer",
    },
    {
      Name: "Employee 31",
      Email: "employee31@example.com",
      Phone: 3456789015,
      Address: "456 Main Road, Cityville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 32",
      Email: "employee32@example.com",
      Phone: 4567890126,
      Address: "555 Elm Avenue, Townsville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 33",
      Email: "employee33@example.com",
      Phone: 5678901237,
      Address: "101 Pine Lane, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "Employee 34",
      Email: "employee34@example.com",
      Phone: 6789012348,
      Address: "789 Oak Road, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Employee 35",
      Email: "employee35@example.com",
      Phone: 7890123459,
      Address: "555 Cedar Street, Suburbia",
      Degree: "Bachelor of Engineering",
      Title: "Project Manager",
    },
    {
      Name: "Employee 36",
      Email: "employee36@example.com",
      Phone: 8901234560,
      Address: "123 Elm Lane, Cityville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 37",
      Email: "employee37@example.com",
      Phone: 9012345671,
      Address: "456 Oak Road, Townsville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 38",
      Email: "employee38@example.com",
      Phone: 1234567892,
      Address: "101 Maple Street, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "Employee 39",
      Email: "employee39@example.com",
      Phone: 2345678903,
      Address: "555 Pine Avenue, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Employee 40",
      Email: "employee40@example.com",
      Phone: 3456789014,
      Address: "789 Cedar Road, Suburbia",
      Degree: "Bachelor of Arts",
      Title: "Content Writer",
    },
    {
      Name: "Employee 41",
      Email: "employee41@example.com",
      Phone: 4567890125,
      Address: "123 Main Street, Cityville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 42",
      Email: "employee42@example.com",
      Phone: 5678901236,
      Address: "456 Elm Lane, Townsville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 43",
      Email: "employee43@example.com",
      Phone: 6789012347,
      Address: "555 Oak Road, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
    {
      Name: "Employee 44",
      Email: "employee44@example.com",
      Phone: 7890123458,
      Address: "101 Pine Street, Hamletville",
      Degree: "Master of Science",
      Title: "Data Scientist",
    },
    {
      Name: "Employee 45",
      Email: "employee45@example.com",
      Phone: 8901234569,
      Address: "789 Cedar Avenue, Suburbia",
      Degree: "Bachelor of Engineering",
      Title: "Project Manager",
    },
    {
      Name: "Employee 46",
      Email: "employee46@example.com",
      Phone: 9012345670,
      Address: "123 Elm Avenue, Cityville",
      Degree: "Master of Fine Arts",
      Title: "Graphic Designer",
    },
    {
      Name: "Employee 47",
      Email: "employee47@example.com",
      Phone: 1234567891,
      Address: "456 Oak Street, Townsville",
      Degree: "Bachelor of Science",
      Title: "Software Engineer",
    },
    {
      Name: "Employee 48",
      Email: "employee48@example.com",
      Phone: 2345678902,
      Address: "101 Pine Lane, Villagetown",
      Degree: "Bachelor of Business Administration",
      Title: "Marketing Manager",
    },
  ],
};
export default data;
